# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ASUS/Desktop/SEA-master/Examples/FPGA/4.Module-Interface/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/rgb2dvi_0_1/rgb2dvi_0.xci
# IP: The module: 'rgb2dvi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Desktop/SEA-master/Examples/FPGA/4.Module-Interface/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/rgb2dvi_0_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/SEA-master/Examples/FPGA/4.Module-Interface/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/rgb2dvi_0_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/SEA-master/Examples/FPGA/4.Module-Interface/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/rgb2dvi_0_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ASUS/Desktop/SEA-master/Examples/FPGA/4.Module-Interface/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/rgb2dvi_0_1/rgb2dvi_0.xci
# IP: The module: 'rgb2dvi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Desktop/SEA-master/Examples/FPGA/4.Module-Interface/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/rgb2dvi_0_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/SEA-master/Examples/FPGA/4.Module-Interface/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/rgb2dvi_0_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ASUS/Desktop/SEA-master/Examples/FPGA/4.Module-Interface/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/rgb2dvi_0_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
